name: Angular CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint || echo "Lint warnings found"

      - name: Build application
        run: npm run build -- --configuration=production

      - name: Ensure target directory exists on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_TOKEN }}
          script: |
            sudo mkdir -p /var/www/media-dashboard
            sudo chown $USER:$USER /var/www/media-dashboard

      - name: Copy built files to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_TOKEN }}
          source: "dist/media-dashboard/*"
          target: "/var/www/media-dashboard"

      - name: Restart Node.js app using PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_TOKEN }}
          script: |
            pm2 reload media-dashboard || pm2 start /var/www/media-dashboard/server.js --name media-dashboard
